version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: new_password
      MYSQL_DATABASE: temporary
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"

  web:
    build: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      REDIS_ADDR: redis:6380
    depends_on:
      - mysql
      - redis
